"""STEWARD seed catalog. Images: TheMealDB (free food photo API, used for academic demo)."""

CATEGORIES = ['Starters',
 'Mains',
 'Biryani & Rice',
 'Noodles & Pasta',
 'Pizza',
 'Burgers & Sandwiches',
 'Wraps & Rolls',
 'Salads & Bowls',
 'Soups',
 'Sides',
 'Desserts',
 'Beverages']

RESTAURANTS = [{'name': 'Spice Route Kitchen',
  'slug': 'spice-route-kitchen',
  'cuisine': 'North Indian, Mughlai',
  'description': 'Slow-cooked curries, tandoor classics and dum biryanis from the kitchens of Delhi and '
                 'Lucknow.',
  'address': '12th Main Road, Indiranagar',
  'city': 'Bengaluru',
  'phone': '+918041234501',
  'avg_delivery_minutes': 35,
  'delivery_fee': 39,
  'min_order_amount': 149,
  'image_url': 'https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg',
  'dishes': [{'name': 'Chicken Handi',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 2,
              'price': 289,
              'stock': 40,
              'description': 'Boneless chicken simmered in a clay handi with onion-tomato masala, cream and '
                             'kasuri methi.',
              'ingredients': 'chicken, onion, tomato, cream, garam masala, kasuri methi',
              'image_url': 'https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg'},
             {'name': 'Tandoori Chicken (Half)',
              'category': 'Starters',
              'food_type': 'NON_VEG',
              'spice_level': 2,
              'price': 319,
              'stock': 30,
              'description': 'Chicken marinated overnight in yoghurt and Kashmiri chilli, charred in the '
                             'tandoor. Smoky and spicy.',
              'ingredients': 'chicken, yoghurt, kashmiri chilli, ginger, garlic, lemon',
              'image_url': 'https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg'},
             {'name': 'Mutton Rogan Josh',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 3,
              'price': 389,
              'stock': 25,
              'description': 'Kashmiri-style tender mutton in a fiery red gravy of whole spices and ratan '
                             'jot.',
              'ingredients': 'mutton, kashmiri chilli, fennel, dry ginger, yoghurt',
              'image_url': 'https://www.themealdb.com/images/media/meals/vvstvq1487342592.jpg'},
             {'name': 'Lucknowi Mutton Biryani',
              'category': 'Biryani & Rice',
              'food_type': 'NON_VEG',
              'spice_level': 2,
              'price': 349,
              'stock': 30,
              'description': 'Fragrant basmati layered with slow-cooked mutton, saffron and fried onions, '
                             'sealed and cooked on dum.',
              'ingredients': 'basmati rice, mutton, saffron, fried onion, mint, ghee',
              'image_url': 'https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg'},
             {'name': 'Matar Paneer',
              'category': 'Mains',
              'food_type': 'VEG',
              'spice_level': 1,
              'price': 229,
              'stock': 45,
              'description': 'Soft cottage cheese cubes and green peas in a mildly spiced tomato gravy. '
                             'Comforting and rich.',
              'ingredients': 'paneer, green peas, tomato, cashew, cream',
              'image_url': 'https://www.themealdb.com/images/media/meals/xxpqsy1511452222.jpg'},
             {'name': 'Dal Fry',
              'category': 'Mains',
              'food_type': 'VEG',
              'spice_level': 1,
              'price': 179,
              'stock': 60,
              'description': 'Yellow toor dal tempered with ghee, cumin, garlic and dried red chilli. Light '
                             'and wholesome.',
              'ingredients': 'toor dal, ghee, cumin, garlic, red chilli',
              'image_url': 'https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg'},
             {'name': 'Rajma Masala',
              'category': 'Mains',
              'food_type': 'VEG',
              'spice_level': 1,
              'price': 189,
              'stock': 50,
              'description': 'Punjabi kidney beans slow-cooked in a thick onion-tomato gravy. Best with '
                             'steamed rice.',
              'ingredients': 'kidney beans, onion, tomato, ginger, garam masala',
              'image_url': 'https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg'},
             {'name': 'Baingan Bharta',
              'category': 'Mains',
              'food_type': 'VEG',
              'spice_level': 2,
              'price': 199,
              'stock': 35,
              'description': 'Fire-roasted smoky aubergine mashed with onions, tomatoes, green chilli and '
                             'coriander.',
              'ingredients': 'aubergine, onion, tomato, green chilli, coriander',
              'image_url': 'https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg'},
             {'name': 'Kesar Phirni',
              'category': 'Desserts',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 119,
              'stock': 40,
              'description': 'Chilled ground-rice pudding with saffron, cardamom and pistachio, set in a '
                             'clay pot.',
              'ingredients': 'rice, milk, saffron, cardamom, pistachio, sugar',
              'image_url': 'https://www.themealdb.com/images/media/meals/dm8kee1779553541.jpg'}]},
 {'name': 'Coastal Curry Co.',
  'slug': 'coastal-curry-co',
  'cuisine': 'Coastal, Goan, Bengali',
  'description': "Seafood and coconut curries from India's coastline — Goa, Mangaluru, Kerala and Bengal.",
  'address': '80 Feet Road, Koramangala 4th Block',
  'city': 'Bengaluru',
  'phone': '+918041234502',
  'avg_delivery_minutes': 40,
  'delivery_fee': 49,
  'min_order_amount': 199,
  'image_url': 'https://www.themealdb.com/images/media/meals/uwxusv1487344500.jpg',
  'dishes': [{'name': 'Goan Recheado Fish Fry',
              'category': 'Starters',
              'food_type': 'NON_VEG',
              'spice_level': 3,
              'price': 379,
              'stock': 20,
              'description': 'Pomfret stuffed with a hot, tangy Goan recheado masala of red chillies and '
                             'vinegar, pan-fried crisp.',
              'ingredients': 'pomfret, red chilli, vinegar, garlic, cumin',
              'image_url': 'https://www.themealdb.com/images/media/meals/uwxusv1487344500.jpg'},
             {'name': 'Malabar Prawn Curry',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 2,
              'price': 399,
              'stock': 25,
              'description': 'Juicy prawns in a coconut milk curry with kokum, curry leaves and green '
                             'chilli.',
              'ingredients': 'prawns, coconut milk, kokum, curry leaves, green chilli',
              'image_url': 'https://www.themealdb.com/images/media/meals/qqlwv91763501559.jpg'},
             {'name': 'Kolkata Chicken Curry',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 2,
              'price': 269,
              'stock': 35,
              'description': 'Bengali-style chicken and potato curry with mustard oil and whole garam '
                             'masala.',
              'ingredients': 'chicken, potato, mustard oil, onion, garam masala',
              'image_url': 'https://www.themealdb.com/images/media/meals/9ya6o71780262651.jpg'},
             {'name': 'Macher Jhol',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 1,
              'price': 299,
              'stock': 20,
              'description': 'Light Bengali fish stew with radish, turmeric and panch phoron. Homestyle and '
                             'soothing.',
              'ingredients': 'fish, radish, turmeric, panch phoron, mustard oil',
              'image_url': 'https://www.themealdb.com/images/media/meals/r7mcjm1780261264.jpg'},
             {'name': 'Cashew Chicken Curry',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 1,
              'price': 289,
              'stock': 30,
              'description': 'Mangalorean chicken in a creamy roasted cashew and coconut gravy. Mild and '
                             'nutty.',
              'ingredients': 'chicken, cashew, coconut, onion, spices',
              'image_url': 'https://www.themealdb.com/images/media/meals/yxsurp1511304301.jpg'},
             {'name': 'Kerala Vegetable Stew',
              'category': 'Mains',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 219,
              'stock': 40,
              'description': 'Seasonal vegetables in a delicate coconut milk stew with whole spices. Mild '
                             'and healthy.',
              'ingredients': 'carrot, beans, potato, coconut milk, curry leaves',
              'image_url': 'https://www.themealdb.com/images/media/meals/4k8nzy1763583384.jpg'},
             {'name': 'Steamed Basmati Rice',
              'category': 'Sides',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 89,
              'stock': 80,
              'description': 'Fluffy long-grain basmati, the perfect partner for any curry.',
              'ingredients': 'basmati rice',
              'image_url': 'https://www.themealdb.com/images/media/meals/kw92t41604181871.jpg'},
             {'name': 'Mango Custard',
              'category': 'Desserts',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 129,
              'stock': 30,
              'description': 'Layered Alphonso mango and vanilla custard, served chilled.',
              'ingredients': 'mango, milk, custard, sugar',
              'image_url': 'https://www.themealdb.com/images/media/meals/u1gisz1784732667.jpg'}]},
 {'name': 'Wok & Roll',
  'slug': 'wok-and-roll',
  'cuisine': 'Indo-Chinese, Pan-Asian',
  'description': 'Fiery Indo-Chinese favourites and Sichuan classics, tossed in a smoking-hot wok.',
  'address': 'HSR Layout Sector 2',
  'city': 'Bengaluru',
  'phone': '+918041234503',
  'avg_delivery_minutes': 30,
  'delivery_fee': 29,
  'min_order_amount': 149,
  'image_url': 'https://www.themealdb.com/images/media/meals/1525872624.jpg',
  'dishes': [{'name': 'Kung Pao Chicken',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 3,
              'price': 299,
              'stock': 35,
              'description': 'Wok-tossed chicken with dried red chillies, Sichuan pepper and roasted '
                             'peanuts. Hot and numbing.',
              'ingredients': 'chicken, dried red chilli, sichuan pepper, peanuts, soy sauce',
              'image_url': 'https://www.themealdb.com/images/media/meals/1525872624.jpg'},
             {'name': 'Chilli Garlic Chicken',
              'category': 'Starters',
              'food_type': 'NON_VEG',
              'spice_level': 3,
              'price': 279,
              'stock': 35,
              'description': 'Crispy chicken tossed in a sticky, spicy chilli-garlic sauce with spring '
                             'onions.',
              'ingredients': 'chicken, garlic, red chilli, soy sauce, spring onion',
              'image_url': 'https://www.themealdb.com/images/media/meals/1529444113.jpg'},
             {'name': 'Chicken Lollipop',
              'category': 'Starters',
              'food_type': 'NON_VEG',
              'spice_level': 3,
              'price': 249,
              'stock': 30,
              'description': 'Frenched chicken wings fried crisp and coated in spicy Schezwan sauce.',
              'ingredients': 'chicken wings, schezwan sauce, garlic, cornflour',
              'image_url': 'https://www.themealdb.com/images/media/meals/nz0lg71784671684.jpg'},
             {'name': 'Chicken Fried Rice',
              'category': 'Biryani & Rice',
              'food_type': 'NON_VEG',
              'spice_level': 1,
              'price': 229,
              'stock': 50,
              'description': 'Wok-fried rice with chicken, egg, vegetables and a dash of soy.',
              'ingredients': 'rice, chicken, egg, spring onion, soy sauce',
              'image_url': 'https://www.themealdb.com/images/media/meals/wuyd2h1765655837.jpg'},
             {'name': 'Sweet and Sour Chicken',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 0,
              'price': 269,
              'stock': 30,
              'description': 'Crispy chicken with peppers and pineapple in a tangy sweet-and-sour glaze. Not '
                             'spicy.',
              'ingredients': 'chicken, bell pepper, pineapple, vinegar, tomato',
              'image_url': 'https://www.themealdb.com/images/media/meals/arzs741766434335.jpg'},
             {'name': 'Kung Po Prawns',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 3,
              'price': 349,
              'stock': 20,
              'description': 'Prawns stir-fried with chillies, cashews and Sichuan pepper.',
              'ingredients': 'prawns, dried chilli, cashew, sichuan pepper',
              'image_url': 'https://www.themealdb.com/images/media/meals/1525873040.jpg'},
             {'name': 'Sichuan Eggplant',
              'category': 'Mains',
              'food_type': 'VEG',
              'spice_level': 2,
              'price': 219,
              'stock': 30,
              'description': 'Silky aubergine in a garlicky, spicy and slightly sweet Sichuan sauce.',
              'ingredients': 'aubergine, garlic, chilli bean paste, ginger',
              'image_url': 'https://www.themealdb.com/images/media/meals/1oz4nb1765687990.jpg'},
             {'name': 'Mapo Tofu (Veg)',
              'category': 'Mains',
              'food_type': 'VEG',
              'spice_level': 3,
              'price': 249,
              'stock': 25,
              'description': 'Soft tofu in a fiery, numbing chilli bean sauce with mushrooms. Vegetarian '
                             'version.',
              'ingredients': 'tofu, chilli bean paste, sichuan pepper, mushroom',
              'image_url': 'https://www.themealdb.com/images/media/meals/1525874812.jpg'},
             {'name': 'Veg Hakka Noodles',
              'category': 'Noodles & Pasta',
              'food_type': 'VEG',
              'spice_level': 1,
              'price': 199,
              'stock': 45,
              'description': 'Thin noodles tossed with crunchy vegetables, garlic and soy in a hot wok.',
              'ingredients': 'noodles, cabbage, carrot, capsicum, soy sauce',
              'image_url': 'https://www.themealdb.com/images/media/meals/1529444830.jpg'},
             {'name': 'Crispy Veg Spring Rolls',
              'category': 'Starters',
              'food_type': 'VEG',
              'spice_level': 1,
              'price': 169,
              'stock': 40,
              'description': 'Golden rolls stuffed with cabbage, carrot and glass noodles, with sweet chilli '
                             'dip.',
              'ingredients': 'cabbage, carrot, glass noodles, spring roll sheet',
              'image_url': 'https://www.themealdb.com/images/media/meals/grhn401765687086.jpg'},
             {'name': 'Hot and Sour Soup (Veg)',
              'category': 'Soups',
              'food_type': 'VEG',
              'spice_level': 2,
              'price': 139,
              'stock': 40,
              'description': 'Peppery, tangy soup with tofu, mushrooms and bamboo shoots.',
              'ingredients': 'tofu, mushroom, bamboo shoot, vinegar, white pepper',
              'image_url': 'https://www.themealdb.com/images/media/meals/1529445893.jpg'}]},
 {'name': 'Green Bowl',
  'slug': 'green-bowl',
  'cuisine': 'Healthy, Salads, Mediterranean',
  'description': 'Fresh salads, grain bowls and smoothies — balanced, high-protein and full of colour.',
  'address': '100 Feet Road, Indiranagar',
  'city': 'Bengaluru',
  'phone': '+918041234504',
  'avg_delivery_minutes': 25,
  'delivery_fee': 29,
  'min_order_amount': 199,
  'image_url': 'https://www.themealdb.com/images/media/meals/1549542994.jpg',
  'dishes': [{'name': 'Salmon Avocado Salad',
              'category': 'Salads & Bowls',
              'food_type': 'NON_VEG',
              'spice_level': 0,
              'price': 449,
              'stock': 15,
              'description': 'Grilled Norwegian salmon over greens with avocado, cucumber and a lemon-dill '
                             'dressing. High protein.',
              'ingredients': 'salmon, avocado, lettuce, cucumber, lemon, dill',
              'image_url': 'https://www.themealdb.com/images/media/meals/1549542994.jpg'},
             {'name': 'Greek Chicken Quinoa Bowl',
              'category': 'Salads & Bowls',
              'food_type': 'NON_VEG',
              'spice_level': 0,
              'price': 349,
              'stock': 25,
              'description': 'Grilled chicken, quinoa, feta, olives, tomato and cucumber with oregano '
                             'vinaigrette. Healthy and filling.',
              'ingredients': 'chicken, quinoa, feta, olives, tomato, cucumber',
              'image_url': 'https://www.themealdb.com/images/media/meals/k29viq1585565980.jpg'},
             {'name': 'Quinoa Stuffed Peppers',
              'category': 'Salads & Bowls',
              'food_type': 'VEG',
              'spice_level': 1,
              'price': 299,
              'stock': 20,
              'description': 'Roasted bell peppers filled with quinoa, black beans, corn and smoked paprika. '
                             'Vegan friendly.',
              'ingredients': 'bell pepper, quinoa, black beans, corn, paprika',
              'image_url': 'https://www.themealdb.com/images/media/meals/b66myb1683207208.jpg'},
             {'name': 'Falafel Pita with Tahini',
              'category': 'Wraps & Rolls',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 249,
              'stock': 30,
              'description': 'Crisp chickpea falafel in warm pita with pickled onions, greens and tahini.',
              'ingredients': 'chickpeas, pita, tahini, onion, parsley',
              'image_url': 'https://www.themealdb.com/images/media/meals/ae6clc1760524712.jpg'},
             {'name': 'Hummus & Veggie Platter',
              'category': 'Starters',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 219,
              'stock': 30,
              'description': 'Creamy hummus with olive oil and paprika, served with crudités and pita.',
              'ingredients': 'chickpeas, tahini, olive oil, carrot, cucumber, pita',
              'image_url': 'https://www.themealdb.com/images/media/meals/gpon5u1763801180.jpg'},
             {'name': 'Pomegranate Salad',
              'category': 'Salads & Bowls',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 229,
              'stock': 25,
              'description': 'Pomegranate, walnuts, greens and feta with a light honey-lime dressing. Fresh '
                             'and light.',
              'ingredients': 'pomegranate, walnut, lettuce, feta, lime',
              'image_url': 'https://www.themealdb.com/images/media/meals/fqpqml1764359125.jpg'},
             {'name': 'Tofu & Cashew Greens Stir-fry',
              'category': 'Salads & Bowls',
              'food_type': 'VEG',
              'spice_level': 1,
              'price': 269,
              'stock': 25,
              'description': 'Tofu with seasonal greens and cashews in a light ginger-soy glaze. Low oil, '
                             'high protein.',
              'ingredients': 'tofu, bok choy, cashew, ginger, soy sauce',
              'image_url': 'https://www.themealdb.com/images/media/meals/minfsc1763766806.jpg'},
             {'name': 'Chickpea Fajita Bowl',
              'category': 'Salads & Bowls',
              'food_type': 'VEG',
              'spice_level': 2,
              'price': 259,
              'stock': 25,
              'description': 'Spiced roasted chickpeas, peppers and onions with salsa and brown rice.',
              'ingredients': 'chickpeas, bell pepper, onion, salsa, brown rice',
              'image_url': 'https://www.themealdb.com/images/media/meals/tvtxpq1511464705.jpg'},
             {'name': 'Creamy Mango Smoothie',
              'category': 'Beverages',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 149,
              'stock': 40,
              'description': 'Alphonso mango blended with yoghurt and a touch of honey.',
              'ingredients': 'mango, yoghurt, honey',
              'image_url': 'https://www.themealdb.com/images/media/meals/pjbaq11784731571.jpg'},
             {'name': 'Chocolate Avocado Mousse',
              'category': 'Desserts',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 179,
              'stock': 20,
              'description': 'Rich, dairy-free dark chocolate mousse made with avocado. Guilt-free dessert.',
              'ingredients': 'avocado, cocoa, maple syrup',
              'image_url': 'https://www.themealdb.com/images/media/meals/uttuxy1511382180.jpg'}]},
 {'name': 'Napoli Street',
  'slug': 'napoli-street',
  'cuisine': 'Italian, Pizza, Pasta',
  'description': 'Wood-fired pizzas and fresh pasta made the Italian way, with a lot of cheese.',
  'address': 'Church Street',
  'city': 'Bengaluru',
  'phone': '+918041234505',
  'avg_delivery_minutes': 35,
  'delivery_fee': 49,
  'min_order_amount': 249,
  'image_url': 'https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg',
  'dishes': [{'name': 'Margherita Pizza',
              'category': 'Pizza',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 299,
              'stock': 40,
              'description': 'Wood-fired base with San Marzano tomato, fresh mozzarella and basil. Cheesy '
                             'classic.',
              'ingredients': 'pizza dough, tomato, mozzarella, basil, olive oil',
              'image_url': 'https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg'},
             {'name': 'Fettuccine Alfredo',
              'category': 'Noodles & Pasta',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 309,
              'stock': 35,
              'description': 'Ribbon pasta in a rich, creamy parmesan and butter sauce. Extra cheesy.',
              'ingredients': 'fettuccine, parmesan, butter, cream',
              'image_url': 'https://www.themealdb.com/images/media/meals/0jv5gx1661040802.jpg'},
             {'name': 'Penne Arrabbiata',
              'category': 'Noodles & Pasta',
              'food_type': 'VEG',
              'spice_level': 2,
              'price': 279,
              'stock': 40,
              'description': 'Penne in a spicy tomato and garlic sauce with chilli flakes and basil.',
              'ingredients': 'penne, tomato, garlic, chilli flakes, basil',
              'image_url': 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg'},
             {'name': 'Spinach & Ricotta Cannelloni',
              'category': 'Noodles & Pasta',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 329,
              'stock': 20,
              'description': 'Pasta tubes filled with spinach and ricotta, baked with tomato sauce and '
                             'melted cheese.',
              'ingredients': 'pasta, spinach, ricotta, mozzarella, tomato',
              'image_url': 'https://www.themealdb.com/images/media/meals/wspuvp1511303478.jpg'},
             {'name': 'Chicken Lasagne',
              'category': 'Noodles & Pasta',
              'food_type': 'NON_VEG',
              'spice_level': 1,
              'price': 369,
              'stock': 20,
              'description': 'Layers of pasta, slow-cooked chicken ragù, béchamel and bubbling mozzarella.',
              'ingredients': 'pasta sheets, chicken, tomato, bechamel, mozzarella',
              'image_url': 'https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg'},
             {'name': 'Chicken Alfredo Primavera',
              'category': 'Noodles & Pasta',
              'food_type': 'NON_VEG',
              'spice_level': 0,
              'price': 349,
              'stock': 25,
              'description': 'Grilled chicken and spring vegetables in creamy alfredo sauce. Cheesy and '
                             'comforting.',
              'ingredients': 'pasta, chicken, broccoli, peas, parmesan, cream',
              'image_url': 'https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg'},
             {'name': 'Chilli Prawn Linguine',
              'category': 'Noodles & Pasta',
              'food_type': 'NON_VEG',
              'spice_level': 2,
              'price': 419,
              'stock': 15,
              'description': 'Linguine with garlic prawns, red chilli, cherry tomatoes and rocket.',
              'ingredients': 'linguine, prawns, chilli, garlic, cherry tomato',
              'image_url': 'https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg'},
             {'name': 'Salmon & Prawn Risotto',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 0,
              'price': 469,
              'stock': 15,
              'description': 'Creamy arborio risotto with salmon, prawns, lemon and parmesan.',
              'ingredients': 'arborio rice, salmon, prawns, parmesan, lemon',
              'image_url': 'https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg'},
             {'name': 'New York Cheesecake',
              'category': 'Desserts',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 229,
              'stock': 20,
              'description': 'Dense, creamy baked cheesecake on a buttery biscuit base.',
              'ingredients': 'cream cheese, biscuit, butter, sugar',
              'image_url': 'https://www.themealdb.com/images/media/meals/swttys1511385853.jpg'}]},
 {'name': 'Burger Theory',
  'slug': 'burger-theory',
  'cuisine': 'American, Burgers, Fast Food',
  'description': 'Smash burgers, crispy fried chicken and loaded sides. Comfort food done right.',
  'address': 'Brigade Road',
  'city': 'Bengaluru',
  'phone': '+918041234506',
  'avg_delivery_minutes': 25,
  'delivery_fee': 29,
  'min_order_amount': 149,
  'image_url': 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg',
  'dishes': [{'name': 'Double Chicken Smash Burger',
              'category': 'Burgers & Sandwiches',
              'food_type': 'NON_VEG',
              'spice_level': 1,
              'price': 279,
              'stock': 40,
              'description': 'Two smashed chicken patties, cheddar, pickles and house sauce in a toasted '
                             'brioche bun.',
              'ingredients': 'chicken patty, cheddar, brioche, pickles, lettuce',
              'image_url': 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg'},
             {'name': 'Crispy Chicken Sandwich',
              'category': 'Burgers & Sandwiches',
              'food_type': 'NON_VEG',
              'spice_level': 1,
              'price': 249,
              'stock': 40,
              'description': 'Buttermilk-fried chicken thigh, slaw and spicy mayo on a soft bun.',
              'ingredients': 'chicken thigh, buttermilk, slaw, mayo, bun',
              'image_url': 'https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg'},
             {'name': 'Chicken & Halloumi Burger',
              'category': 'Burgers & Sandwiches',
              'food_type': 'NON_VEG',
              'spice_level': 0,
              'price': 299,
              'stock': 25,
              'description': 'Grilled chicken breast with grilled halloumi, tomato and herb mayo.',
              'ingredients': 'chicken breast, halloumi, tomato, lettuce, bun',
              'image_url': 'https://www.themealdb.com/images/media/meals/vdwloy1713225718.jpg'},
             {'name': 'Southern Fried Chicken (6 pc)',
              'category': 'Starters',
              'food_type': 'NON_VEG',
              'spice_level': 1,
              'price': 349,
              'stock': 30,
              'description': 'Crunchy, juicy fried chicken in a secret blend of herbs and spices.',
              'ingredients': 'chicken, flour, paprika, black pepper, herbs',
              'image_url': 'https://www.themealdb.com/images/media/meals/40r49m1763197022.jpg'},
             {'name': 'Peri-Peri Chicken Wings',
              'category': 'Starters',
              'food_type': 'NON_VEG',
              'spice_level': 3,
              'price': 259,
              'stock': 35,
              'description': 'Extra-crispy wings tossed in hot peri-peri sauce. Very spicy.',
              'ingredients': 'chicken wings, peri-peri, garlic, lemon',
              'image_url': 'https://www.themealdb.com/images/media/meals/feh9k21784665694.jpg'},
             {'name': 'Chicken Fajita Mac & Cheese',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 2,
              'price': 289,
              'stock': 25,
              'description': 'Baked macaroni in a three-cheese sauce with spicy fajita chicken. Ultimate '
                             'cheesy comfort.',
              'ingredients': 'macaroni, cheddar, mozzarella, chicken, fajita spice',
              'image_url': 'https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg'},
             {'name': 'Grilled Mac & Cheese Sandwich',
              'category': 'Burgers & Sandwiches',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 199,
              'stock': 30,
              'description': 'Creamy mac and cheese grilled between buttery sourdough slices. Cheesy '
                             'overload.',
              'ingredients': 'macaroni, cheddar, sourdough, butter',
              'image_url': 'https://www.themealdb.com/images/media/meals/xutquv1505330523.jpg'},
             {'name': 'Loaded Potato Wedges',
              'category': 'Sides',
              'food_type': 'VEG',
              'spice_level': 1,
              'price': 149,
              'stock': 50,
              'description': 'Seasoned skin-on wedges with cheese sauce, jalapeños and sour cream.',
              'ingredients': 'potato, cheese sauce, jalapeno, sour cream',
              'image_url': 'https://www.themealdb.com/images/media/meals/1550441882.jpg'},
             {'name': 'Chocolate Raspberry Brownie',
              'category': 'Desserts',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 149,
              'stock': 30,
              'description': 'Fudgy dark chocolate brownie with tart raspberries.',
              'ingredients': 'dark chocolate, butter, flour, raspberry',
              'image_url': 'https://www.themealdb.com/images/media/meals/yypvst1511386427.jpg'}]},
 {'name': 'Levant Grill',
  'slug': 'levant-grill',
  'cuisine': 'Middle Eastern, Lebanese, Turkish',
  'description': 'Charcoal-grilled kebabs, shawarma and mezze from Beirut to Istanbul.',
  'address': 'Jayanagar 4th Block',
  'city': 'Bengaluru',
  'phone': '+918041234507',
  'avg_delivery_minutes': 30,
  'delivery_fee': 39,
  'min_order_amount': 199,
  'image_url': 'https://www.themealdb.com/images/media/meals/hcg6l91763596970.jpg',
  'dishes': [{'name': 'Chicken Shawarma Plate',
              'category': 'Wraps & Rolls',
              'food_type': 'NON_VEG',
              'spice_level': 1,
              'price': 249,
              'stock': 40,
              'description': 'Spit-roasted chicken shawarma with garlic toum, pickles and warm flatbread.',
              'ingredients': 'chicken, garlic, yoghurt, flatbread, pickles',
              'image_url': 'https://www.themealdb.com/images/media/meals/hcg6l91763596970.jpg'},
             {'name': 'Adana Mutton Kebab',
              'category': 'Starters',
              'food_type': 'NON_VEG',
              'spice_level': 2,
              'price': 349,
              'stock': 25,
              'description': 'Hand-minced mutton kebab with red pepper and sumac, grilled over charcoal.',
              'ingredients': 'mutton, red pepper, sumac, onion, parsley',
              'image_url': 'https://www.themealdb.com/images/media/meals/04axct1763793018.jpg'},
             {'name': 'Smoky Chicken Skewers',
              'category': 'Starters',
              'food_type': 'NON_VEG',
              'spice_level': 1,
              'price': 299,
              'stock': 30,
              'description': 'Shish tawook — chicken skewers marinated in yoghurt, lemon and smoked paprika.',
              'ingredients': 'chicken, yoghurt, lemon, smoked paprika, garlic',
              'image_url': 'https://www.themealdb.com/images/media/meals/3um6il1763794322.jpg'},
             {'name': 'Spicy Mutton Wrap',
              'category': 'Wraps & Rolls',
              'food_type': 'NON_VEG',
              'spice_level': 3,
              'price': 289,
              'stock': 25,
              'description': 'Hot cumin-spiced mutton with crunchy slaw and spicy mayo in a soft wrap.',
              'ingredients': 'mutton, cumin, chilli, cabbage slaw, wrap',
              'image_url': 'https://www.themealdb.com/images/media/meals/jyylmo1763790808.jpg'},
             {'name': 'Turkish Mutton Pilau',
              'category': 'Biryani & Rice',
              'food_type': 'NON_VEG',
              'spice_level': 1,
              'price': 329,
              'stock': 20,
              'description': 'Buttery rice pilaf with tender mutton, chickpeas and warm spices.',
              'ingredients': 'rice, mutton, chickpeas, butter, cinnamon',
              'image_url': 'https://www.themealdb.com/images/media/meals/cr2kyr1763793839.jpg'},
             {'name': 'Shakshuka',
              'category': 'Mains',
              'food_type': 'NON_VEG',
              'spice_level': 2,
              'price': 239,
              'stock': 25,
              'description': 'Eggs poached in a spiced tomato and pepper sauce, with bread for dipping. '
                             'Contains egg.',
              'ingredients': 'eggs, tomato, bell pepper, cumin, paprika',
              'image_url': 'https://www.themealdb.com/images/media/meals/eo0yfb1763600916.jpg'},
             {'name': 'Falafel Mezze Plate',
              'category': 'Starters',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 219,
              'stock': 35,
              'description': 'Crisp herb falafel with hummus, tabbouleh and tahini.',
              'ingredients': 'chickpeas, parsley, tahini, bulgur, lemon',
              'image_url': 'https://www.themealdb.com/images/media/meals/u5e9qq1763795441.jpg'},
             {'name': 'Grilled Aubergine & Hummus',
              'category': 'Mains',
              'food_type': 'VEG',
              'spice_level': 1,
              'price': 239,
              'stock': 25,
              'description': 'Chargrilled aubergine slices over hummus with pomegranate and herbs.',
              'ingredients': 'aubergine, hummus, pomegranate, mint',
              'image_url': 'https://www.themealdb.com/images/media/meals/zub3s91764110535.jpg'},
             {'name': 'Pistachio Baklava',
              'category': 'Desserts',
              'food_type': 'VEG',
              'spice_level': 0,
              'price': 189,
              'stock': 30,
              'description': 'Flaky filo layered with pistachios and walnuts, soaked in honey syrup.',
              'ingredients': 'filo pastry, pistachio, walnut, honey, butter',
              'image_url': 'https://www.themealdb.com/images/media/meals/ytme8t1764111401.jpg'}]}]
